<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.5.57">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="RIZKY DAMAR WICAKSONO SURBAKTI">
<meta name="dcterms.date" content="2025-01-14">

<title>Strategi Peningkatan Ekspor Kopi Indonesia di Pasar Global Dari Tahun 2012-2023</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="index_files/libs/clipboard/clipboard.min.js"></script>
<script src="index_files/libs/quarto-html/quarto.js"></script>
<script src="index_files/libs/quarto-html/popper.min.js"></script>
<script src="index_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="index_files/libs/quarto-html/anchor.min.js"></script>
<link href="index_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="index_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="index_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="index_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="index_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">


</head>

<body>

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
<div class="quarto-alternate-formats"><h2>Other Formats</h2><ul><li><a href="index.docx"><i class="bi bi-file-word"></i>MS Word</a></li></ul></div></div>
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Strategi Peningkatan Ekspor Kopi Indonesia di Pasar Global Dari Tahun 2012-2023</h1>
<p class="subtitle lead">Metode Penelitian Politeknik APP Jakarta</p>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>RIZKY DAMAR WICAKSONO SURBAKTI </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">January 14, 2025</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="poltekapp.jpg" class="img-fluid figure-img"></p>
<figcaption>logo APP</figcaption>
</figure>
</div>
<section id="pendahuluan" class="level2" data-number="1">
<h2 data-number="1" class="anchored" data-anchor-id="pendahuluan"><span class="header-section-number">1</span> Pendahuluan</h2>
<section id="latar-belakang" class="level3" data-number="1.1">
<h3 data-number="1.1" class="anchored" data-anchor-id="latar-belakang"><span class="header-section-number">1.1</span> Latar belakang</h3>
<p>Indonesia merupakan salah satu produsen kopi terbesar dan terkenal di dunia, dengan dua jenis kopi utama, yaitu kopi arabika dan robusta, yang dihasilkan di berbagai daerah penghasil kopi seperti Sumatra, Sulawesi, dan Jawa. Kopi Indonesia tidak hanya memiliki kualitas yang diakui secara internasional, tetapi juga memiliki ragam cita rasa yang khas, menjadikannya komoditas unggulan dalam perekonomian nasional. Seiring dengan pertumbuhan konsumsi kopi global, Indonesia memiliki peluang besar untuk memperluas ekspor kopi ke pasar internasional. Namun, meskipun memiliki potensi yang besar, sektor ekspor kopi Indonesia menghadapi sejumlah tantangan yang menghambat optimalisasi kontribusinya terhadap perekonomian nasional. Dari tahun 2012 hingga 2023, sektor ekspor kopi Indonesia menunjukkan tren yang fluktuatif. Meskipun volume ekspor kopi Indonesia relatif stabil, negara ini harus bersaing dengan produsen kopi besar lainnya, seperti Brasil dan Vietnam, yang juga menawarkan kopi berkualitas tinggi dengan harga yang kompetitif. Salah satu tantangan terbesar yang dihadapi oleh sektor ekspor kopi Indonesia adalah kurangnya diversifikasi produk dan pengemasan yang inovatif, yang membatasi daya saing produk kopi Indonesia di pasar global. Selain itu, masalah ketidakstabilan kualitas kopi dan kurangnya promosi serta branding kopi Indonesia di pasar internasional turut menghambat peningkatan ekspor. Pada saat yang sama, pasar kopi global terus berkembang dengan pesat, terutama di negara-negara berkembang dan pasar baru. Permintaan akan kopi berkualitas tinggi, terutama kopi spesialti, semakin meningkat. Hal ini memberikan peluang bagi kopi Indonesia untuk memasuki pasar-pasar baru dan memperkuat posisinya di pasar internasional. Namun, tantangan dalam meningkatkan produksi dan distribusi kopi yang memenuhi standar internasional serta memperkuat daya saing produk Indonesia masih perlu mendapat perhatian serius. Untuk menghadapi tantangan ini, dibutuhkan strategi peningkatan ekspor kopi yang komprehensif, yang mencakup perbaikan di sektor kualitas produk, peningkatan kapasitas produksi, serta perluasan jaringan distribusi internasional. Selain itu, pengembangan brand kopi Indonesia dan promosi yang lebih efektif di pasar global sangat penting untuk meningkatkan daya tarik kopi Indonesia di mata konsumen dunia. Makalah ini bertujuan untuk menganalisis perkembangan ekspor kopi Indonesia dari tahun 2012 hingga 2023 serta strategi-strategi yang dapat diterapkan untuk meningkatkan ekspor kopi Indonesia di pasar global. Dengan strategi yang tepat, diharapkan sektor kopi Indonesia dapat lebih kompetitif, berkontribusi lebih besar terhadap perekonomian, dan memperkuat posisi Indonesia sebagai salah satu pemain utama dalam industri kopi dunia.</p>
</section>
<section id="ruang-lingkup" class="level3" data-number="1.2">
<h3 data-number="1.2" class="anchored" data-anchor-id="ruang-lingkup"><span class="header-section-number">1.2</span> Ruang lingkup</h3>
<p>Strategi Peningkatan Ekspor Kopi Indonesia di Pasar Global Dari Tahun 2012 – 2023 Data Untuk Penelitian ini di Ambil Dari Badan Pusat Statistik (BPS), Penelitian ini Meliputi Analisis Data Ekspor Kopi Indonesia, Tantangan yang Dihadapi oleh Sektor Ekspor Kopi, Peluang di Pasar Kopi Global, Strategi Pengembangan dan Peningkatan Ekspor.</p>
</section>
<section id="rumusan-masalah" class="level3" data-number="1.3">
<h3 data-number="1.3" class="anchored" data-anchor-id="rumusan-masalah"><span class="header-section-number">1.3</span> Rumusan masalah</h3>
<ol type="1">
<li>Apa saja tantangan yang dihadapi oleh sektor ekspor kopi Indonesia dari tahun 2012 hingga 2023?</li>
<li>Strategi apa saja yang dapat diterapkan untuk meningkatkan kualitas produk, kapasitas produksi, dan jaringan distribusi internasional kopi Indonesia?</li>
<li>Bagaimana daya saing kopi Indonesia di pasar global dalam menghadapi persaingan dengan negara penghasil kopi besar lainnya seperti Brasil dan Vietnam?</li>
<li>Apa saja faktor yang menghambat optimalisasi ekspor kopi Indonesia, seperti kualitas produk, diversifikasi, pengemasan, dan promosi internasional?</li>
</ol>
</section>
<section id="tujuan-dan-manfaat-penelitian" class="level3" data-number="1.4">
<h3 data-number="1.4" class="anchored" data-anchor-id="tujuan-dan-manfaat-penelitian"><span class="header-section-number">1.4</span> Tujuan dan manfaat penelitian</h3>
<p>1.Menganalisis Tren Ekspor Kopi Indonesia Dari tahun 2012 - 2023 2. Mengidentifikasi Tantangan Ekspor Kopi 3. Menilai Peluang di Pasar Kopi GlobaL 4. Mengevaluasi Strategi Peningkatan Ekspor kopi</p>
<p>Penelitian ini memberikan manfaat signifikan dalam memperluas pemahaman tentang strategi ekspor kopi Indonesia, khususnya dalam menghadapi tantangan dan peluang di pasar global. Secara praktis, penelitian ini membantu pelaku industri kopi, seperti petani dan eksportir, untuk menentukan strategi yang lebih tepat untuk meningkatkan kualitas produk, diversifikasi, serta memperkuat branding kopi Indonesia di pasar internasional. Selain itu, hasil penelitian ini juga berguna bagi pemerintah dalam merumuskan kebijakan yang mendukung ekspor kopi, seperti regulasi yang memfasilitasi perdagangan dan promosi produk kopi Indonesia. Dengan demikian, penelitian ini dapat memperkuat daya saing kopi Indonesia, mendongkrak kontribusinya terhadap perekonomian nasional, dan memperkuat posisi Indonesia sebagai pemain utama dalam industri kopi global.</p>
</section>
<section id="package" class="level3" data-number="1.5">
<h3 data-number="1.5" class="anchored" data-anchor-id="package"><span class="header-section-number">1.5</span> Package</h3>
<p>Ini tidak wajib ada di tulisan anda tapi anda dapat menunjukkan Packages yang digunakan antara lain sebagai berikut:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co">#/warning: false</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="co">#/echo: true</span></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
✔ dplyr     1.1.4     ✔ readr     2.1.5
✔ forcats   1.0.0     ✔ stringr   1.5.1
✔ ggplot2   3.5.1     ✔ tibble    3.2.1
✔ lubridate 1.9.3     ✔ tidyr     1.3.1
✔ purrr     1.0.2     
── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()
ℹ Use the conflicted package (&lt;http://conflicted.r-lib.org/&gt;) to force all conflicts to become errors</code></pre>
</div>
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readxl)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
</section>
<section id="studi-pustaka" class="level2" data-number="2">
<h2 data-number="2" class="anchored" data-anchor-id="studi-pustaka"><span class="header-section-number">2</span> Studi pustaka</h2>
<p>Studi pustaka dalam penelitian ini mengacu pada berbagai teori dan penelitian sebelumnya yang mendukung strategi peningkatan ekspor kopi Indonesia. Penelitian sebelumnya menunjukkan bahwa kualitas produk, inovasi, branding, dan promosi adalah faktor penting untuk meningkatkan daya saing kopi di pasar global. Beberapa studi juga menyoroti tantangan seperti persaingan dengan negara penghasil kopi besar, masalah harga yang tidak stabil, dan kurangnya diversifikasi produk. Teori keunggulan komparatif dan perdagangan internasional digunakan untuk menganalisis bagaimana Indonesia dapat memanfaatkan potensi kopi untuk bersaing di pasar global. Penelitian ini mengadopsi temuan-temuan tersebut untuk merumuskan strategi peningkatan ekspor kopi Indonesia antara 2012 hingga 2023.</p>
</section>
<section id="metode-penelitian" class="level2" data-number="3">
<h2 data-number="3" class="anchored" data-anchor-id="metode-penelitian"><span class="header-section-number">3</span> Metode penelitian</h2>
<p>kualitatif</p>
<section id="data" class="level3" data-number="3.1">
<h3 data-number="3.1" class="anchored" data-anchor-id="data"><span class="header-section-number">3.1</span> Data</h3>
<p>Berikut adalah tabel data Strategi Peningkatan Ekspor Kopi Indonesia di Pasar Global Dari Tahun 2012 - 2023</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th><strong>Tahun</strong></th>
<th><strong>x</strong></th>
<th><strong>y</strong></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>2012</td>
<td>447063,9</td>
<td>1244146,6</td>
</tr>
<tr class="even">
<td>2013</td>
<td>532156,6</td>
<td>1166235,5</td>
</tr>
<tr class="odd">
<td>2014</td>
<td>382774,5</td>
<td>1030807,2</td>
</tr>
<tr class="even">
<td>2015</td>
<td>499651,3</td>
<td>1189725,4</td>
</tr>
<tr class="odd">
<td>2016</td>
<td>412528,9</td>
<td>1001068,2</td>
</tr>
<tr class="even">
<td>2017</td>
<td>464232,8</td>
<td>1175601,3</td>
</tr>
<tr class="odd">
<td>2018</td>
<td>277475,4</td>
<td>807283,9</td>
</tr>
<tr class="even">
<td>2019</td>
<td>355810,3</td>
<td>872727,3</td>
</tr>
<tr class="odd">
<td>2020</td>
<td>375670,6</td>
<td>809673,7</td>
</tr>
<tr class="even">
<td>2021</td>
<td>384684,9</td>
<td>850100,1</td>
</tr>
<tr class="odd">
<td>2022</td>
<td>433881,1</td>
<td>1136172,3</td>
</tr>
<tr class="even">
<td>2023</td>
<td>276335,2</td>
<td>916578,7</td>
</tr>
</tbody>
</table>
<p>penelitian ini menggunakan data berbentuk time serries dari tahun 2012-2023</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="fu">setwd</span>(<span class="st">"C:/Users/Asus/Desktop/Bahan Rizky/metopel (1)/metopel"</span>)</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>metopen<span class="ot">=</span><span class="fu">read_excel</span>(<span class="st">"dataexel.xlsx"</span>)</span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readxl)</span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a>reg1<span class="ot">&lt;-</span><span class="fu">lm</span>(<span class="at">data =</span>metopen,y<span class="sc">~</span>x)</span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(reg1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = y ~ x, data = metopen)

Residuals:
    Min      1Q  Median      3Q     Max 
-160695  -64392    6699   60742  155075 

Coefficients:
             Estimate Std. Error t value Pr(&gt;|t|)   
(Intercept) 3.458e+05  1.575e+05   2.195  0.05284 . 
x           1.663e+00  3.836e-01   4.334  0.00148 **
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 100200 on 10 degrees of freedom
Multiple R-squared:  0.6526,    Adjusted R-squared:  0.6178 
F-statistic: 18.78 on 1 and 10 DF,  p-value: 0.00148</code></pre>
</div>
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readxl)</span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>metopen<span class="sc">$</span>m <span class="ot">&lt;-</span><span class="fu">resid</span>(reg1)</span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(metopen<span class="sc">$</span>x,metopen<span class="sc">$</span>m,<span class="at">ylab =</span><span class="st">"error"</span>,<span class="at">col=</span><span class="st">'green'</span>)</span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">h=</span><span class="dv">0</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/unnamed-chunk-2-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readxl)</span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>metopen<span class="sc">$</span>m <span class="ot">&lt;-</span><span class="fu">resid</span>(reg1)</span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(metopen<span class="sc">$</span>y,metopen<span class="sc">$</span>m,<span class="at">ylab =</span><span class="st">"error"</span>,<span class="at">col=</span><span class="st">'orange'</span>)</span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">h=</span><span class="dv">0</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/unnamed-chunk-3-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="metode-analisis" class="level3" data-number="3.2">
<h3 data-number="3.2" class="anchored" data-anchor-id="metode-analisis"><span class="header-section-number">3.2</span> Metode analisis</h3>
<p>Metode yang dipilih adalah regresi linear dimana: y=β 0​+β 1​x+ϵ</p>
<p>di mana: 𝑦adalah variabel dependen,</p>
<p>𝑥adalah variabel independen,</p>
<p>𝛽0​adalah intercept (nilai 𝑦saat𝑥=0),</p>
<p>𝛽1​adalah koefisien untuk</p>
<p>𝑥 ϵ adalah error atau gangguan.</p>
<p>Metode regresi linier yang Anda pilih digunakan untuk memodelkan hubungan antara variabel dependen (y) dan variabel independen (x) menggunakan persamaan linear 𝑦=𝛽0+𝛽1𝑥+𝜖. Koefisien yang dihasilkan, 𝛽0 dan 𝛽1,memberi gambaran tentang hubungan antara kedua variabel tersebut, dan ϵ mencerminkan error atau gangguan dalam model.</p>
</section>
</section>
<section id="pembahasan" class="level2" data-number="4">
<h2 data-number="4" class="anchored" data-anchor-id="pembahasan"><span class="header-section-number">4</span> Pembahasan</h2>
<section id="pembahasan-masalah" class="level3" data-number="4.1">
<h3 data-number="4.1" class="anchored" data-anchor-id="pembahasan-masalah"><span class="header-section-number">4.1</span> Pembahasan masalah</h3>
<table class="caption-top table">
<colgroup>
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
</colgroup>
<thead>
<tr class="header">
<th><strong>Aspek</strong></th>
<th><strong>Koefisien / Nilai</strong></th>
<th><strong>Std. Error</strong></th>
<th><strong>t-value</strong></th>
<th><strong>p-value</strong></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Residuals</strong></td>
<td>-160695, -64392, 6699, 60742, 155075</td>
<td>-</td>
<td>-</td>
<td>-</td>
</tr>
<tr class="even">
<td><strong>Intercept</strong></td>
<td>345,800</td>
<td>157,500</td>
<td>2.195</td>
<td>0.05284</td>
</tr>
<tr class="odd">
<td><strong>x (Jumlah Ekspor CPO ke India)</strong></td>
<td>1.663</td>
<td>0.383</td>
<td>4.334</td>
<td>0.00148 **</td>
</tr>
<tr class="even">
<td><strong>Residual Standard Error</strong></td>
<td>100,200</td>
<td>-</td>
<td>-</td>
<td>-</td>
</tr>
<tr class="odd">
<td><strong>Multiple R-squared</strong></td>
<td>0.6526</td>
<td>-</td>
<td>-</td>
<td>-</td>
</tr>
<tr class="even">
<td><strong>Adjusted R-squared</strong></td>
<td>0.6178</td>
<td>-</td>
<td>-</td>
<td>-</td>
</tr>
<tr class="odd">
<td><strong>F-statistic</strong></td>
<td>18.78</td>
<td>-</td>
<td>-</td>
<td>0.00148 **</td>
</tr>
</tbody>
</table>
<p>Koefisien untuk x (jumlah ekspor kopi) menunjukkan hubungan yang signifikan antara ekspor kopi danvariabel dependen y. Setiap peningkatan satu unit ekspor kopi akan meningkatkan y sebesar 1.663 unit. R-squared yang cukup tinggi (0.6526) menunjukkan bahwa model regresi dapat menjelaskan lebih dari 65% variabilitas dalam y, meskipun ada variabilitas lain yang tidak dapat dijelaskan oleh model. p-value yang sangat kecil untuk koefisien x dan F-statistic menunjukkan bahwa model regresi ini secara statistik signifikan dan dapat diandalkan untuk menjelaskan hubungan antara ekspor kopi dan variabel dependen yang diamati.</p>
</section>
</section>
<section id="analisis-masalah" class="level2" data-number="5">
<h2 data-number="5" class="anchored" data-anchor-id="analisis-masalah"><span class="header-section-number">5</span> Analisis masalah</h2>
<p>Hasil regresinya adalah</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readxl)</span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>reg1<span class="ot">&lt;-</span><span class="fu">lm</span>(<span class="at">data =</span>metopen,y<span class="sc">~</span>x)</span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(reg1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = y ~ x, data = metopen)

Residuals:
    Min      1Q  Median      3Q     Max 
-160695  -64392    6699   60742  155075 

Coefficients:
             Estimate Std. Error t value Pr(&gt;|t|)   
(Intercept) 3.458e+05  1.575e+05   2.195  0.05284 . 
x           1.663e+00  3.836e-01   4.334  0.00148 **
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 100200 on 10 degrees of freedom
Multiple R-squared:  0.6526,    Adjusted R-squared:  0.6178 
F-statistic: 18.78 on 1 and 10 DF,  p-value: 0.00148</code></pre>
</div>
</div>
<p>Nilai Koefisien x: 1.663 Interpretasi: Koefisien ini menunjukkan bahwa setiap peningkatan Net Weight (berat bersih ekspor kopi) sebesar 1 unit akan menyebabkan peningkatan nilai FOB (nilai ekspor) sebesar 1.663 unit, dengan asumsi faktor lainnya tetap konstan. p-value untuk x (Net Weight): 0.00148 Interpretasi: Nilai p yang sangat kecil (lebih kecil dari 0.05) menunjukkan bahwa hubungan antara Net Weight dan FOB adalah signifikan secara statistik. Artinya, Net Weight memiliki pengaruh yang nyata terhadap FOB dalam model ini. Hal ini mendukung kesimpulan bahwa peningkatan volume ekspor kopi (berat bersih kopi yang diekspor) akan berpengaruh positif pada peningkatan nilai ekspor (FOB) secara signifikan. Dalam penelitian Anda, strategi peningkatan ekspor kopi dapat difokuskan pada upaya meningkatkan Net Weight atau volume ekspor kopi Indonesia, yang pada gilirannya akan meningkatkan nilai ekspor kopi Indonesia. R-squared dan Adjusted R-squared Multiple R-squared: 0.6526 Adjusted R-squared: 0.6178 Residual standard error: 100200</p>
<p>menunjukkan bahwa hubungan antara Net Weight dan FOB adalah signifikan secara statistik. Artinya, Net Weight memiliki pengaruh yang nyata terhadap FOB dalam model ini.</p>
</section>
<section id="kesimpulan" class="level2" data-number="6">
<h2 data-number="6" class="anchored" data-anchor-id="kesimpulan"><span class="header-section-number">6</span> Kesimpulan</h2>
<p>strategi peningkatan ekspor kopi Indonesia di pasar global dari tahun 2012 hingga 2023. Indonesia, sebagai salah satu produsen kopi terbesar, memiliki potensi besar untuk memperluas ekspor terutama dalam menghadapi pertumbuhan permintaan kopi berkualitas tinggi di pasar internasional. Meskipun demikian, sektor ekspor kopi Indonesia menghadapi berbagai tantangan seperti kurangnya diversifikasi produk, masalah kualitas, dan promosi yang tidak memadai. Analisis menunjukkan bahwa untuk meningkatkan daya saing kopi Indonesia, diperlukan strategi komprehensif yang mencakup peningkatan kualitas produk, pengembangan kapasitas produksi, dan perluasan jaringan distribusi internasional. Selain itu, pentingnya pengembangan branding dan promosi kopi Indonesia di pasar global harus menjadi perhatian utama. Pemerintah dan pelaku usaha diharapkan dapat berkolaborasi untuk merumuskan kebijakan yang mendukung, menyediakan infrastruktur yang lebih baik, dan memanfaatkan teknologi terbaru untuk memenuhi standar internasional. Dengan langkah-langkah ini, diharapkan kopi Indonesia dapat lebih kompetitif, berkontribusi signifikan terhadap perekonomian nasional, dan memperkuat posisinya sebagai pemain utama dalam industri kopi global.</p>
</section>
<section id="referensi" class="level2" data-number="7">
<h2 data-number="7" class="anchored" data-anchor-id="referensi"><span class="header-section-number">7</span> Referensi</h2>
<ol type="1">
<li>Badan Pusat Statistik (BPS). (2023). Statistik Perdagangan Kopi Indonesia 2023. Jakarta: Badan Pusat Statistik.</li>
<li>Direktorat Jenderal Perkebunan Kementerian Pertanian Republik Indonesia. (2024). Laporan Tahunan Perkebunan Kopi di Indonesia. Jakarta: Kementerian Pertanian RI.</li>
<li>Firdaus, A., &amp; Haryanto, E. (2022). Dampak Perubahan Iklim terhadap Produksi Kopi di Indonesia. Jurnal Agribisnis, 18(2), 135-150.</li>
<li>Kementerian Perdagangan Republik Indonesia. (2023). Strategi Pengendalian Impor Produk Pertanian: Studi Kasus Kopi. Jakarta: Kementerian Perdagangan RI.</li>
<li>Nugroho, S. D., &amp; Mulyadi, T. (2024). Kebijakan Perdagangan Kopi dan Pengaruhnya terhadap Industri Lokal: Analisis Impor dan Ekspor Kopi di Indonesia. Jurnal Ekonomi dan Perdagangan, 29(1), 200-215.</li>
<li>Sudirman, Y., &amp; Putra, D. (2021). Peran Teknologi Pertanian dalam Meningkatkan Produktivitas Kopi di Indonesia. Jurnal Teknologi Pertanian, 19(3), 90-104.</li>
<li>Sutanto, P., &amp; Suryani, M. (2023). Peningkatan Daya Saing Kopi Lokal di Pasar Global: Perspektif Ekonomi Agribisnis. Jakarta: Penerbit Agribisnis.</li>
<li>World Coffee Organization. (2023). Global Coffee Trade: Trends and Analysis. Geneva: World Coffee Organization.</li>
<li>Yulianto, B. (2024). Kebijakan Impor dan Dampaknya pada Sektor Kopi Indonesia. Jurnal Ekonomi Pembangunan, 15(4), 42-55.</li>
</ol>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>